import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/models.dart';

/// Builds and shares/prints a PDF report card for a student's term results.
class ReportCardGenerator {
  static Future<void> generateAndShare({
    required Student student,
    required Term term,
    required List<Map<String, dynamic>> resultRows,
  }) async {
    final doc = pw.Document();

    double totalScore = 0;
    double totalMax = 0;
    for (final row in resultRows) {
      totalScore += (row['score'] as num).toDouble();
      totalMax += (row['maxScore'] as num).toDouble();
    }
    final overallPct = totalMax > 0 ? (totalScore / totalMax) * 100 : 0;

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Center(
                child: pw.Text(
                  'Schoollog — Student Report Card',
                  style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
                ),
              ),
              pw.SizedBox(height: 16),
              pw.Text('Name: ${student.fullName}'),
              pw.Text('Admission No: ${student.admissionNo}'),
              pw.Text('Class: ${student.className}'),
              pw.Text('Term: ${term.name} — Session ${term.session}'),
              pw.SizedBox(height: 20),
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey600),
                columnWidths: const {
                  0: pw.FlexColumnWidth(3),
                  1: pw.FlexColumnWidth(1.5),
                  2: pw.FlexColumnWidth(1.5),
                  3: pw.FlexColumnWidth(1.5),
                },
                children: [
                  pw.TableRow(
                    decoration: const pw.BoxDecoration(color: PdfColors.blueGrey100),
                    children: [
                      _cell('Subject', bold: true),
                      _cell('Score', bold: true),
                      _cell('Max', bold: true),
                      _cell('Grade', bold: true),
                    ],
                  ),
                  ...resultRows.map((row) => pw.TableRow(children: [
                        _cell(row['subject'] as String),
                        _cell((row['score'] as num).toString()),
                        _cell((row['maxScore'] as num).toString()),
                        _cell((row['grade'] as String?) ?? '-'),
                      ])),
                ],
              ),
              pw.SizedBox(height: 20),
              pw.Text(
                'Overall: ${totalScore.toStringAsFixed(0)} / ${totalMax.toStringAsFixed(0)} '
                '(${overallPct.toStringAsFixed(1)}%)',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 14),
              ),
              pw.SizedBox(height: 40),
              pw.Text('Generated by Schoollog — offline exam management',
                  style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey)),
            ],
          );
        },
      ),
    );

    await Printing.sharePdf(
      bytes: await doc.save(),
      filename: '${student.fullName.replaceAll(' ', '_')}_${term.name.replaceAll(' ', '_')}_report.pdf',
    );
  }

  static pw.Widget _cell(String text, {bool bold = false}) => pw.Padding(
        padding: const pw.EdgeInsets.all(6),
        child: pw.Text(
          text,
          style: pw.TextStyle(fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal),
        ),
      );
}
